PairID = "USDT"
UseBip32 = false

# source token config
[SrcToken]
# ID must be ERC20 if source token is erc20 token
ID = "ERC20"
Name = "USDTERC20"
Symbol = "USDT"
Decimals = 6
Description = "ERC20 USDT"
# if ID is ERC20, this is the erc20 token's contract address
ContractAddress = "0xaac17f958d2ee523a2206206994597c13d831ec7"
# deposit to this address to make swap
DepositAddress = "0xa3B432914A996b0A48695dF9B2d701edA45FF264"
# withdraw from this address
DcrmAddress = "0xa3B432914A996b0A48695dF9B2d701edA45FF264"
# dcrm account public key
DcrmPubkey = "04a24e3eb6e4a56d54ca0dc15e51a2428b2ae9b4d22e5803e283cfa9c8648ebf9c5f0d338b054755d46c8e7c5287ba47c59973c7f3db21d5284c1f777cbf5bedd4"
# maximum deposit value
MaximumSwap = 200000.0
# minimum deposit value
MinimumSwap = 0.5
# calced deposit fee = deposit value * this rate (when in [min, max] deposit fee range)
SwapFeeRate = 0.0
# maximum deposit fee, if calced deposit fee is larger than this fee, then use this value as deposit fee
MaximumSwapFee = 0.0
# minimum deposit fee, if calced deposit fee is smaller than this fee, then use this value as deposit fee
MinimumSwapFee = 0.0
# plus this percentage of gas price to make tx more easier to be mined in source chain
# corresponding to send asset on source chain (eg. BTC) for withdrawing
PlusGasPricePercentage = 10 # plus 15% gas price
# if deposit value is larger than this value then need more verify strategy
BigValueThreshold = 50000.0
# only aggregate when balace is bigger than this value
AggregateMinValue = 1000.0
# disable deposit function if this flag is true
DisableSwap = false

# dest token config
[DestToken]
ID = "anyUSDT"
Name = "USDT-ERC20"
Symbol = "anyUSDT"
Decimals = 6
Description = "cross chain bridge USDT with anyUSDT"
# mapping erc20 token address
ContractAddress = "0xa46d67fb63770052a07d5b7c14ed858a8c90f825"
# mapping erc20 token creator
DcrmAddress = "0xa3B432914A996b0A48695dF9B2d701edA45FF264"
# dcrm account public key
DcrmPubkey = "04a24e3eb6e4a56d54ca0dc15e51a2428b2ae9b4d22e5803e283cfa9c8648ebf9c5f0d338b054755d46c8e7c5287ba47c59973c7f3db21d5284c1f777cbf5bedd4"
# maximum withdraw value
MaximumSwap = 200000.0
# minimum withdraw value
MinimumSwap = 20.0
# calced withdraw fee = withdraw value * this rate (when in [min, max] withdraw fee range)
SwapFeeRate = 0.001
# maximum withdraw fee, if calced withdraw fee is larger than this fee, then use this value as withdraw fee
MaximumSwapFee = 50.0
# minimum withdraw fee, if calced withdraw fee is smaller than this fee, then use this value as withdraw fee
MinimumSwapFee = 5.0
# plus this percentage of gas price to make tx more easier to be mined in dest chain
# corresponding to send mapping token on dest chain (eg. mBTC) for depositing
PlusGasPricePercentage = 1 # plus 1% gas price
# if withdraw value is larger than this value then need more verify strategy
BigValueThreshold = 20000.0
# disable withdraw function if this flag is true
DisableSwap = false
